### ISSUE TITLE
Take a nap.

### ISSUE THREAD

**Issue by jessekrubin** [sinclairzx81/sidewinder#30]
Hi @sinclairzx81 ,

I played with sidewinder a bit and it's awesome (in the truest sense of the word; not in the "dude these nachos are 'awesome'" sense of the word), but I am genuinely worried that you don't sleep. 

Really great work!
Keep it up,
But take a nap,
Jesse

**Comment by sinclairzx81** [comment]
@jessekrubin Haha, thanks :D

Yeah, Sidewinder is a bit of an interesting project and may be getting some updates over the next few weeks/months (I really do need to merge upstream TB types in on this project). Have been looking at ways to get the service infrastructure running natively on Deno and possibly Bun platforms (i.e. same imports, same code, running on multiple runtimes), but a WIP at this stage (if only platforms could agree on ESM)), I expect once TB gets a little closer to 1.0, this project may ramp up considerably.

For now, will try get some sleep! 😴(zzz)
Cheers!
S
