### ISSUE TITLE
Validation fails when optional type has undefined value

### ISSUE THREAD

**Issue by waikikamoukow** [sinclairzx81/sidewinder#36]
I'm encountering an issue where setting the value of an optional type to undefined fails validation. Adding the following test to `tests/validator/validator.ts` also fails:
```
it('Should validate undefined optional', () => {
    const T = Type.Optional(Type.String())
    const V = new Validator(T)
    const R1 = V.check(undefined)
    Assert.equal(R1.success, true)
  })
```

My understanding is that the above test should pass.

**Comment by sinclairzx81** [comment]
@waikikamoukow Hi!

Optional is a contextual modifier that can only be used to make object properties optional. When it's used outside of an object, the modifier has no effect (so would expect `R1.success` to be `false` for this case), which is correct.

The following shows optional when used outside any context.

```typescript
const T = Type.Optional(Type.String())

// which is represented as 

const T = { type: 'string', [Modifier]: 'Optional' }

// but where symbols are ignored by the json schema spec

const t = { type: 'string' } // string is required
``` 
In TypeBox, the Object function will omit any property from the object schematics' `required` array if it sees Optional applied to that property. In this regard the modifier acts as mapping metadata to help the function understand what should (or shouldn't) be included in the output objects `required` array.

```typescript
const T = Type.Object({                          // const T = {
  x: Type.Optional(Type.Number()),               //   type: 'object',
  y: Type.Number()                               //   properties: {
})                                               //     x: { type: 'number' },
                                                 //     y: { type: 'number' }
                                                 //   },
                                                 //   required: ['y'] <-- x - omitted
                                                 // }
```
To express variable optionality, another way to achieve that is via Union
```typescript
// i.e. let value: undefined | string = undefined

const T = Type.Union([Type.Undefined(), Type.String()])
```
... which can also be used for properties (without Optional)
```typescript
const T = Type.Object({                              // const T = {
  x: Type.Union([Type.Undefined(), Type.Number()]),  //   type: 'object',
  y: Type.Number()                                   //   properties: {
})                                                   //     x: { 
                                                     //       anyOf: [
                                                     //         { type: 'Undefined' },  <- non-standard btw
                                                     //         { type: 'number' }
                                                     //       ]
                                                     //     },
                                                     //     y: { type: 'number' }
                                                     //   },
                                                     //   required: ['x', 'y'] // x is required!
                                                     // }
```
But note that `x` appears on the `required` array, making this property required via `key in` check, and suggesting there's a distinction between optionality (in the context of object properties) and undefined (as applied through Union). Also we also needed to reach for non-standard schematics (undefined) to express the intent here. These concepts aspects are very much at the intersection of Json Schema and TypeScript semantics.

Based on the above, the recommend way to handle optional (or potential for missing value), is through Union of `T | null` when encoding for the json specification specifically (recommended)

```typescript
const T = Type.Union([Type.String(), Type.Null()]) // supported by the spec!
```
Some extended schema specifications (such as OpenAPI) provide a `nullable` as a short hand to express this concept (which is a reflectable property), Sidewinder (and TB) uses the standard Json Schema form (which is expressed as `anyOf`)

Hope this helps! Will close off this issue for now :)
Cheers!
